//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrandBlueResortandSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int bookid { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string nationalId { get; set; }
        public string dob { get; set; }
        public string nationality { get; set; }
        public string selectedroom { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }

        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> EntityValidationErrors { get; }
    }

}
