//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrandBlueResortandSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public int RoomId { get; set; }
        public int osv { get; set; }
        public int fv { get; set; }
        public int ds { get; set; }
        public int ps { get; set; }
        public int osr { get; set; }
    }
}
